language: python

python:
  - "3.6"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - flake8 -v
  - pytest -v
  - mypy --ignore-missing-imports test/. -v
  - mypy --ignore-missing-imports data/. -v
  - mypy --ignore-missing-imports app/. -v